# infra/docker-compose.yml
version: "3.8"
services:
  db-habitforge:
    image: postgres:16-alpine
    container_name: postgres-autik
    env_file:
      - .env # Inyecta las variables exclusivas del contenedor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
