### 1. Obtener todos los hábitos (Prueba del Verbo GET)
# Nota: Cambia el puerto 5157 por el puerto real que te arroje la terminal
GET http://localhost:5159/api/Vehiculo
Accept: application/json

### 2. Crear un nuevo hábito (Prueba del Verbo POST)
POST http://localhost:5159/api/Vehiculo
Content-Type: application/json

{
  "id": 2,
  "vehiculoId": 2,
  "tallerId": 2,
  "fecha": "2026-09-28T23:15:00Z",
  "kilometraje": 100,
  "descripcion": "Vehiculo ciudad",
  "costo": 150000
}
